#--------
#全局配置
#--------

# 头像
avatar: /img/avatar.jpg
# 用户名
username: 'Samoyeder'


# 分类图片
cate_img: /img/category/cat1.png

# 博客title
title: 'Hello World'

# 备案信息
beian: 京ICP备20006979号

# 搜索栏
search:
  enable: true
  path: /local-search.xml # 文件引用地址，默认是下方生成位置，也可以将生成后的 local-search.xml 上传到其它位置引用，如：https://www.example.com/local-search.xml
  generate_path: /local-search.xml # 文件生成位置，必须为相对位置
  field: post
  content: true

#------
#导航栏
#------
# 分页配置
menu:
  home: /
  categories: /categories
  tags: /tags
  archives: /archives
  about: /about


#----------
#页脚footer
#----------

# 站点运行开始时间
time:
  enable: true
  year: 2019 # 年份
  month: 11 # 月份
  date: 15 # 日期
  hour: 00 # 小时
  minute: 00 # 分钟
  second: 00 # 秒